### ISSUE TITLE
For Review [1px]

### ISSUE THREAD

**Issue by shahzaman900** [AliRezaBmeDu/recipe-app#9]
- The link to our kanban board is: https://github.com/AliRezaBmeDu/recipe-app/projects/1
- We are working with 2 team members on this project

**Comment by mikethreels** [comment]
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- good job using the correct layout of the board

## Required Changes ♻️
- [ ] According to the requirements each card should have a number of points assigned corresponding with the amount of hours you expect to spend on it, after that the cards should be divided between the team members so the workload for each team member is more or less equal.
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by binhussen** [comment]
Hi @AliRezaBmeDu and @sheezu900 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
![IApproveSimonCowellGIF (6)](https://github.com/AliRezaBmeDu/recipe-app/assets/52010789/49a38f31-9bb6-44e6-8ed6-09abc61e2014)

## Highlights
- Aranged Kanban Board ✔️
- Added Estimated Time✔️
- Farly Distributed Tasks ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
